import {
  GripVertical,
  Plus,
  ChevronRight,
  ChevronDown,
  Search,
  Trash2,
  Copy,
  Replace,
  Link,
  Image,
  Bold,
  Italic,
  Underline,
  Strikethrough,
  Code,
  Heading1,
  Heading2,
  Heading3,
  Pilcrow,
  List,
  ListOrdered,
  ListChecks,
  Quote,
  Info,
  Table,
  Minus,
  FileCode,
  Bookmark,
  PanelsTopLeft,
  X,
  Check,
  FileText,
  MoreHorizontal,
  Star,
  Clock,
  User,
  Settings,
  Palette,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  ArrowDown,
  CircleX,
  Columns3,
  type LucideIcon,
} from 'lucide-react'

const ICON_MAP: Record<string, LucideIcon> = {
  drag: GripVertical,
  plus: Plus,
  'chev-r': ChevronRight,
  'chev-d': ChevronDown,
  search: Search,
  trash: Trash2,
  copy: Copy,
  convert: Replace,
  link: Link,
  img: Image,
  bold: Bold,
  italic: Italic,
  under: Underline,
  strike: Strikethrough,
  code: Code,
  h1: Heading1,
  h2: Heading2,
  h3: Heading3,
  paragraph: Pilcrow,
  bullet: List,
  numbered: ListOrdered,
  todo: ListChecks,
  quote: Quote,
  callout: Info,
  table: Table,
  divider: Minus,
  'code-block': FileCode,
  bookmark: Bookmark,
  tabs: PanelsTopLeft,
  columns: Columns3,
  x: X,
  check: Check,
  doc: FileText,
  more: MoreHorizontal,
  star: Star,
  clock: Clock,
  user: User,
  settings: Settings,
  color: Palette,
  'insert-left': ArrowLeft,
  'insert-right': ArrowRight,
  'insert-above': ArrowUp,
  'insert-below': ArrowDown,
  'x-circle': CircleX,
}

export function Icon({ name, size = 14 }: { name: string; size?: number }) {
  const Component = ICON_MAP[name]
  if (!Component) return <span aria-hidden="true" style={{ display: 'inline-block', width: size, height: size }} />
  return (
    <span aria-hidden="true" style={{ display: 'inline-flex', verticalAlign: 'middle', flex: 'none' }}>
      <Component size={size} strokeWidth={1.5} />
    </span>
  )
}
