apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: migration-hub

resources:
  - namespace.yaml
  - secrets.yaml
  - configmap.yaml
  - pvc-uploads.yaml
  - postgres.yaml
  - backend-api.yaml
  - backend-worker.yaml
  - frontend.yaml
  - ingress.yaml
